[Settings]
# 再生したいMP4ファイルのパス
FILE_PATH = test4-long.mp4

[AudioDevices]
# 音声デバイスのUID
UID_1 = BuiltInHeadphoneOutputDevice
UID_2 = BuiltInSpeakerDevice

[SeekPoints]
# シークポイントのリスト (番号="タイトル"=hh:mm:ss:fr)
# ※ fr は 60fps におけるフレーム数 (0〜59)
01 = "Opening"=00:00:00:00
02 = "A_Part"=00:02:03:00
03 = "B_Part"=00:03:30:00
04 = "Ending"=00:06:45:30
05 = "additional"=00:52:13:41